name: Tests

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / rust ${{ matrix.rust-version }} ${{ matrix.build-type }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rust-version: stable
            build-type: release
            cargo-build-flags: --release
          - os: ubuntu-22.04
            rust-version: 1.64
            build-type: debug

    steps:
      - uses: actions/checkout@v3

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: run tests
        run: cargo test ${{ matrix.cargo-build-flags }}

      - name: check the code against sympy
        run: |
          pip install .
          pip install sympy
          python test_vs_sympy.py

      - name: check that benchmarks compile and run once
        if: matrix.build-type == 'release'
        run: |
          cd benchmarks
          cargo bench -- --test
